### PR TITLE
Fixed a typo

### PR DESCRIPTION
**Pull request by thewhitetulip**
Spelling mistake of Directory

### CODE REVIEW

**Comment by 88250** [comment]
Thank you! :grapes:

**Comment by thewhitetulip** [comment]
Nice work with this webIDE!! I was going to build one eventually :+1: I'll now contribute to this one instead :smile: 

IDEs are better off being webserver apps since we can code on browsers using even a phone and they are platform independent

**Comment by 88250** [comment]
[Here](http://hacpai.com/article/1438407961481) is the goal of Wide, maybe you need use Google Translate to read it.

Thank you again!

**Comment by thewhitetulip** [comment]
Seems about right :+1: but they can totally replace desktop IDEs :ghost:

**Pull request merged**
